/*
 * Selling Partner API for Reports
 * The Selling Partner API for Reports lets you retrieve and manage a variety of reports that can help selling partners manage their businesses.
 *
 * OpenAPI spec version: 2021-06-30
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.29
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../../src/reports_2021-06-30/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../../src/reports_2021-06-30/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SellingPartnerApiForReports);
  }
}(this, function(expect, SellingPartnerApiForReports) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new SellingPartnerApiForReports.ReportsApi();
  });

  describe('reports_2021-06-30', function() {
    describe('ReportsApi', function() {
      describe('cancelReport', function() {
        it('should call cancelReport successfully', function(done) {
          // TODO: uncomment, update parameter values for cancelReport call
          /*
          var reportId = "reportId_example";

          instance.cancelReport(reportId).then(function(data) {

            done();
          }, function(error) {
            done(error);
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('cancelReportSchedule', function() {
        it('should call cancelReportSchedule successfully', function(done) {
          // TODO: uncomment, update parameter values for cancelReportSchedule call
          /*
          var reportScheduleId = "reportScheduleId_example";

          instance.cancelReportSchedule(reportScheduleId).then(function(data) {

            done();
          }, function(error) {
            done(error);
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('createReport', function() {
        it('should call createReport successfully', function(done) {
          // TODO: uncomment, update parameter values for createReport call and complete the assertions
          /*
          var body = new SellingPartnerApiForReports.CreateReportSpecification();
          body.reportOptions = new SellingPartnerApiForReports.ReportOptions();
          body.reportType = "";
          body.dataStartTime = new Date();
          body.dataEndTime = new Date();
          body.marketplaceIds = [""];

          instance.createReport(body).then(function(data) {
            // TODO: update response assertions
            expect(data).to.be.a(SellingPartnerApiForReports.CreateReportResponse);
            expect(data.reportId).to.be.a('string');
            // expect(data.reportId).to.be("");

            done();
          }, function(error) {
            done(error);
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('createReportSchedule', function() {
        it('should call createReportSchedule successfully', function(done) {
          // TODO: uncomment, update parameter values for createReportSchedule call and complete the assertions
          /*
          var body = new SellingPartnerApiForReports.CreateReportScheduleSpecification();
          body.reportType = "";
          body.marketplaceIds = [""];
          body.reportOptions = new SellingPartnerApiForReports.ReportOptions();
          body.period = "PT5M";
          body.nextReportCreationTime = new Date();

          instance.createReportSchedule(body).then(function(data) {
            // TODO: update response assertions
            expect(data).to.be.a(SellingPartnerApiForReports.CreateReportScheduleResponse);
            expect(data.reportScheduleId).to.be.a('string');
            // expect(data.reportScheduleId).to.be("");

            done();
          }, function(error) {
            done(error);
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('getReport', function() {
        it('should call getReport successfully', function(done) {
          // TODO: uncomment, update parameter values for getReport call and complete the assertions
          /*
          var reportId = "reportId_example";

          instance.getReport(reportId).then(function(data) {
            // TODO: update response assertions
            expect(data).to.be.a(SellingPartnerApiForReports.Report);
            {
              let dataCtr = data.marketplaceIds;
              expect(dataCtr).to.be.an(Array);
              expect(dataCtr).to.not.be.empty();
              for (let p in dataCtr) {
                let data = dataCtr[p];
                expect(data).to.be.a('string');
                // expect(data).to.be("");
              }
            }
            expect(data.reportId).to.be.a('string');
            // expect(data.reportId).to.be("");
            expect(data.reportType).to.be.a('string');
            // expect(data.reportType).to.be("");
            expect(data.dataStartTime).to.be.a(Date);
            // expect(data.dataStartTime).to.be(new Date());
            expect(data.dataEndTime).to.be.a(Date);
            // expect(data.dataEndTime).to.be(new Date());
            expect(data.reportScheduleId).to.be.a('string');
            // expect(data.reportScheduleId).to.be("");
            expect(data.createdTime).to.be.a(Date);
            // expect(data.createdTime).to.be(new Date());
            expect(data.processingStatus).to.be.a('string');
            // expect(data.processingStatus).to.be("CANCELLED");
            expect(data.processingStartTime).to.be.a(Date);
            // expect(data.processingStartTime).to.be(new Date());
            expect(data.processingEndTime).to.be.a(Date);
            // expect(data.processingEndTime).to.be(new Date());
            expect(data.reportDocumentId).to.be.a('string');
            // expect(data.reportDocumentId).to.be("");

            done();
          }, function(error) {
            done(error);
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('getReportDocument', function() {
        it('should call getReportDocument successfully', function(done) {
          // TODO: uncomment, update parameter values for getReportDocument call and complete the assertions
          /*
          var reportDocumentId = "reportDocumentId_example";

          instance.getReportDocument(reportDocumentId).then(function(data) {
            // TODO: update response assertions
            expect(data).to.be.a(SellingPartnerApiForReports.ReportDocument);
            expect(data.reportDocumentId).to.be.a('string');
            // expect(data.reportDocumentId).to.be("");
            expect(data.url).to.be.a('string');
            // expect(data.url).to.be("");
            expect(data.compressionAlgorithm).to.be.a('string');
            // expect(data.compressionAlgorithm).to.be("GZIP");

            done();
          }, function(error) {
            done(error);
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('getReportSchedule', function() {
        it('should call getReportSchedule successfully', function(done) {
          // TODO: uncomment, update parameter values for getReportSchedule call and complete the assertions
          /*
          var reportScheduleId = "reportScheduleId_example";

          instance.getReportSchedule(reportScheduleId).then(function(data) {
            // TODO: update response assertions
            expect(data).to.be.a(SellingPartnerApiForReports.ReportSchedule);
            expect(data.reportScheduleId).to.be.a('string');
            // expect(data.reportScheduleId).to.be("");
            expect(data.reportType).to.be.a('string');
            // expect(data.reportType).to.be("");
            {
              let dataCtr = data.marketplaceIds;
              expect(dataCtr).to.be.an(Array);
              expect(dataCtr).to.not.be.empty();
              for (let p in dataCtr) {
                let data = dataCtr[p];
                expect(data).to.be.a('string');
                // expect(data).to.be("");
              }
            }
            expect(data.reportOptions).to.be.a(SellingPartnerApiForReports.ReportOptions);
                expect(data.period).to.be.a('string');
            // expect(data.period).to.be("");
            expect(data.nextReportCreationTime).to.be.a(Date);
            // expect(data.nextReportCreationTime).to.be(new Date());

            done();
          }, function(error) {
            done(error);
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('getReportSchedules', function() {
        it('should call getReportSchedules successfully', function(done) {
          // TODO: uncomment, update parameter values for getReportSchedules call and complete the assertions
          /*
          var reportTypes = ["reportTypes_example"];

          instance.getReportSchedules(reportTypes).then(function(data) {
            // TODO: update response assertions
            expect(data).to.be.a(SellingPartnerApiForReports.ReportScheduleList);
            {
              let dataCtr = data.reportSchedules;
              expect(dataCtr).to.be.an(Array);
              expect(dataCtr).to.not.be.empty();
              for (let p in dataCtr) {
                let data = dataCtr[p];
                expect(data).to.be.a(SellingPartnerApiForReports.ReportSchedule);
                expect(data.reportScheduleId).to.be.a('string');
                // expect(data.reportScheduleId).to.be("");
                expect(data.reportType).to.be.a('string');
                // expect(data.reportType).to.be("");
                {
                  let dataCtr = data.marketplaceIds;
                  expect(dataCtr).to.be.an(Array);
                  expect(dataCtr).to.not.be.empty();
                  for (let p in dataCtr) {
                    let data = dataCtr[p];
                    expect(data).to.be.a('string');
                    // expect(data).to.be("");
                  }
                }
                expect(data.reportOptions).to.be.a(SellingPartnerApiForReports.ReportOptions);
                    expect(data.period).to.be.a('string');
                // expect(data.period).to.be("");
                expect(data.nextReportCreationTime).to.be.a(Date);
                // expect(data.nextReportCreationTime).to.be(new Date());
              }
            }

            done();
          }, function(error) {
            done(error);
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('getReports', function() {
        it('should call getReports successfully', function(done) {
          // TODO: uncomment, update parameter values for getReports call and complete the assertions
          /*
          var opts = {};
          opts.reportTypes = ["reportTypes_example"];
          opts.processingStatuses = ["processingStatuses_example"];
          opts.marketplaceIds = ["marketplaceIds_example"];
          opts.pageSize = 10;
          opts.createdSince = new Date("2013-10-20T19:20:30+01:00");
          opts.createdUntil = new Date("2013-10-20T19:20:30+01:00");
          opts.nextToken = "nextToken_example";

          instance.getReports(opts).then(function(data) {
            // TODO: update response assertions
            expect(data).to.be.a(SellingPartnerApiForReports.GetReportsResponse);
            expect(data.reports).to.be.a(SellingPartnerApiForReports.ReportList);
                expect(data.nextToken).to.be.a('string');
            // expect(data.nextToken).to.be("");

            done();
          }, function(error) {
            done(error);
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
