/*
 * Selling Partner API for Pricing
 * The Selling Partner API for Pricing helps you programmatically retrieve product pricing and offer pricing information for Amazon Marketplace products.  For more information, refer to the [Product Pricing v2022-05-01 Use Case Guide](https://developer-docs.amazon.com/sp-api/docs/product-pricing-api-v2022-05-01-use-case-guide).
 *
 * OpenAPI spec version: 2022-05-01
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.29
 *
 * Do not edit the class manually.
 *
 */

import {ApiClient} from '../ApiClient.js';
import {FeaturedOffer} from './FeaturedOffer.js';
import {FeaturedOfferExpectedPrice} from './FeaturedOfferExpectedPrice.js';

/**
 * The FeaturedOfferExpectedPriceResult model module.
 * @module productPricing_2022-05-01/js-client.productPricing_2022-05-01.model/FeaturedOfferExpectedPriceResult
 * @version 2022-05-01
 */
export class FeaturedOfferExpectedPriceResult {
  /**
   * Constructs a new <code>FeaturedOfferExpectedPriceResult</code>.
   * The featured offer expected price result data for the requested offer.
   * @alias module:productPricing_2022-05-01/js-client.productPricing_2022-05-01.model/FeaturedOfferExpectedPriceResult
   * @class
   * @param resultStatus {String} The status of the featured offer expected price computation. Possible values include `VALID_FOEP`, `NO_COMPETING_OFFER`, `OFFER_NOT_ELIGIBLE`, `OFFER_NOT_FOUND`, `ASIN_NOT_ELIGIBLE`. Additional values may be added in the future.
   */
  constructor(resultStatus) {
    this.resultStatus = resultStatus;
  }

  /**
   * Constructs a <code>FeaturedOfferExpectedPriceResult</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:productPricing_2022-05-01/js-client.productPricing_2022-05-01.model/FeaturedOfferExpectedPriceResult} obj Optional instance to populate.
   * @return {module:productPricing_2022-05-01/js-client.productPricing_2022-05-01.model/FeaturedOfferExpectedPriceResult} The populated <code>FeaturedOfferExpectedPriceResult</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      switch(typeof data) {
        case 'string':
          obj = String(data);
          break;
        case 'number':
          obj = Number(data);
          break;
        case 'boolean':
          obj = Boolean(data);
          break;
      }
      obj = obj || new FeaturedOfferExpectedPriceResult();
      if (data.hasOwnProperty('featuredOfferExpectedPrice'))
        obj.featuredOfferExpectedPrice = FeaturedOfferExpectedPrice.constructFromObject(data['featuredOfferExpectedPrice']);
      if (data.hasOwnProperty('resultStatus'))
        obj.resultStatus = ApiClient.convertToType(data['resultStatus'], 'String');
      if (data.hasOwnProperty('competingFeaturedOffer'))
        obj.competingFeaturedOffer = FeaturedOffer.constructFromObject(data['competingFeaturedOffer']);
      if (data.hasOwnProperty('currentFeaturedOffer'))
        obj.currentFeaturedOffer = FeaturedOffer.constructFromObject(data['currentFeaturedOffer']);
    }
    return obj;
  }
}

/**
 * @member {module:productPricing_2022-05-01/js-client.productPricing_2022-05-01.model/FeaturedOfferExpectedPrice} featuredOfferExpectedPrice
 */
FeaturedOfferExpectedPriceResult.prototype.featuredOfferExpectedPrice = undefined;

/**
 * The status of the featured offer expected price computation. Possible values include `VALID_FOEP`, `NO_COMPETING_OFFER`, `OFFER_NOT_ELIGIBLE`, `OFFER_NOT_FOUND`, `ASIN_NOT_ELIGIBLE`. Additional values may be added in the future.
 * @member {String} resultStatus
 */
FeaturedOfferExpectedPriceResult.prototype.resultStatus = undefined;

/**
 * The offer that will likely be the featured offer if the target offer is priced above its featured offer expected price. If the target offer is currently the featured offer, this property will be different than `currentFeaturedOffer`.
 * @member {module:productPricing_2022-05-01/js-client.productPricing_2022-05-01.model/FeaturedOffer} competingFeaturedOffer
 */
FeaturedOfferExpectedPriceResult.prototype.competingFeaturedOffer = undefined;

/**
 * The offer that is currently the featured offer. If the target offer is not currently featured, then this property will be equal to `competingFeaturedOffer`.
 * @member {module:productPricing_2022-05-01/js-client.productPricing_2022-05-01.model/FeaturedOffer} currentFeaturedOffer
 */
FeaturedOfferExpectedPriceResult.prototype.currentFeaturedOffer = undefined;


