/*
 * Selling Partner API for Orders
 * Use the Orders Selling Partner API to programmatically retrieve order information. With this API, you can develop fast, flexible, and custom applications to manage order synchronization, perform order research, and create demand-based decision support tools.   _Note:_ For the JP, AU, and SG marketplaces, the Orders API supports orders from 2016 onward. For all other marketplaces, the Orders API supports orders for the last two years (orders older than this don't show up in the response).
 *
 * OpenAPI spec version: v0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.29
 *
 * Do not edit the class manually.
 *
 */

import {ApiClient} from '../ApiClient.js';
import {OtherDeliveryAttributes} from './OtherDeliveryAttributes.js';
import {PreferredDeliveryTime} from './PreferredDeliveryTime.js';

/**
 * The DeliveryPreferences model module.
 * @module ordersV0/js-client.ordersV0.model/DeliveryPreferences
 * @version v0
 */
export class DeliveryPreferences {
  /**
   * Constructs a new <code>DeliveryPreferences</code>.
   * Contains all of the delivery instructions provided by the customer for the shipping address.
   * @alias module:ordersV0/js-client.ordersV0.model/DeliveryPreferences
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>DeliveryPreferences</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:ordersV0/js-client.ordersV0.model/DeliveryPreferences} obj Optional instance to populate.
   * @return {module:ordersV0/js-client.ordersV0.model/DeliveryPreferences} The populated <code>DeliveryPreferences</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      switch(typeof data) {
        case 'string':
          obj = String(data);
          break;
        case 'number':
          obj = Number(data);
          break;
        case 'boolean':
          obj = Boolean(data);
          break;
      }
      obj = obj || new DeliveryPreferences();
      if (data.hasOwnProperty('DropOffLocation'))
        obj.dropOffLocation = ApiClient.convertToType(data['DropOffLocation'], 'String');
      if (data.hasOwnProperty('PreferredDeliveryTime'))
        obj.preferredDeliveryTime = PreferredDeliveryTime.constructFromObject(data['PreferredDeliveryTime']);
      if (data.hasOwnProperty('OtherAttributes'))
        obj.otherAttributes = ApiClient.convertToType(data['OtherAttributes'], [OtherDeliveryAttributes]);
      if (data.hasOwnProperty('AddressInstructions'))
        obj.addressInstructions = ApiClient.convertToType(data['AddressInstructions'], 'String');
    }
    return obj;
  }
}

/**
 * Drop-off location selected by the customer.
 * @member {String} dropOffLocation
 */
DeliveryPreferences.prototype.dropOffLocation = undefined;

/**
 * Business hours and days when the delivery is preferred.
 * @member {module:ordersV0/js-client.ordersV0.model/PreferredDeliveryTime} preferredDeliveryTime
 */
DeliveryPreferences.prototype.preferredDeliveryTime = undefined;

/**
 * Enumerated list of miscellaneous delivery attributes associated with the shipping address.
 * @member {Array.<module:ordersV0/js-client.ordersV0.model/OtherDeliveryAttributes>} otherAttributes
 */
DeliveryPreferences.prototype.otherAttributes = undefined;

/**
 * Building instructions, nearby landmark or navigation instructions.
 * @member {String} addressInstructions
 */
DeliveryPreferences.prototype.addressInstructions = undefined;


