/*
 * Selling Partner API for Orders
 * Use the Orders Selling Partner API to programmatically retrieve order information. With this API, you can develop fast, flexible, and custom applications to manage order synchronization, perform order research, and create demand-based decision support tools.   _Note:_ For the JP, AU, and SG marketplaces, the Orders API supports orders from 2016 onward. For all other marketplaces, the Orders API supports orders for the last two years (orders older than this don't show up in the response).
 *
 * OpenAPI spec version: v0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.29
 *
 * Do not edit the class manually.
 *
 */

import {ApiClient} from '../ApiClient.js';
import {ErrorList} from './ErrorList.js';
import {OrderItemsBuyerInfoList} from './OrderItemsBuyerInfoList.js';

/**
 * The GetOrderItemsBuyerInfoResponse model module.
 * @module ordersV0/js-client.ordersV0.model/GetOrderItemsBuyerInfoResponse
 * @version v0
 */
export class GetOrderItemsBuyerInfoResponse {
  /**
   * Constructs a new <code>GetOrderItemsBuyerInfoResponse</code>.
   * The response schema for the `getOrderItemsBuyerInfo` operation.
   * @alias module:ordersV0/js-client.ordersV0.model/GetOrderItemsBuyerInfoResponse
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>GetOrderItemsBuyerInfoResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:ordersV0/js-client.ordersV0.model/GetOrderItemsBuyerInfoResponse} obj Optional instance to populate.
   * @return {module:ordersV0/js-client.ordersV0.model/GetOrderItemsBuyerInfoResponse} The populated <code>GetOrderItemsBuyerInfoResponse</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      switch(typeof data) {
        case 'string':
          obj = String(data);
          break;
        case 'number':
          obj = Number(data);
          break;
        case 'boolean':
          obj = Boolean(data);
          break;
      }
      obj = obj || new GetOrderItemsBuyerInfoResponse();
      if (data.hasOwnProperty('payload'))
        obj.payload = OrderItemsBuyerInfoList.constructFromObject(data['payload']);
      if (data.hasOwnProperty('errors'))
        obj.errors = ErrorList.constructFromObject(data['errors']);
    }
    return obj;
  }
}

/**
 * The payload for the `getOrderItemsBuyerInfo` operation.
 * @member {module:ordersV0/js-client.ordersV0.model/OrderItemsBuyerInfoList} payload
 */
GetOrderItemsBuyerInfoResponse.prototype.payload = undefined;

/**
 * One or more unexpected errors occurred during the `getOrderItemsBuyerInfo` operation.
 * @member {module:ordersV0/js-client.ordersV0.model/ErrorList} errors
 */
GetOrderItemsBuyerInfoResponse.prototype.errors = undefined;


