/*
 * Selling Partner API for Orders
 * Use the Orders Selling Partner API to programmatically retrieve order information. With this API, you can develop fast, flexible, and custom applications to manage order synchronization, perform order research, and create demand-based decision support tools.   _Note:_ For the JP, AU, and SG marketplaces, the Orders API supports orders from 2016 onward. For all other marketplaces, the Orders API supports orders for the last two years (orders older than this don't show up in the response).
 *
 * OpenAPI spec version: v0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.29
 *
 * Do not edit the class manually.
 *
 */

import {ApiClient} from '../ApiClient.js';

/**
 * The RegulatedInformationField model module.
 * @module ordersV0/js-client.ordersV0.model/RegulatedInformationField
 * @version v0
 */
export class RegulatedInformationField {
  /**
   * Constructs a new <code>RegulatedInformationField</code>.
   * A field collected from the regulatory form.
   * @alias module:ordersV0/js-client.ordersV0.model/RegulatedInformationField
   * @class
   * @param fieldId {String} The unique identifier of the field.
   * @param fieldLabel {String} The name of the field.
   * @param fieldType {module:ordersV0/js-client.ordersV0.model/RegulatedInformationField.FieldTypeEnum} The type of field.
   * @param fieldValue {String} The content of the field as collected in regulatory form. Note that `FileAttachment` type fields contain a URL where you can download the attachment.
   */
  constructor(fieldId, fieldLabel, fieldType, fieldValue) {
    this.fieldId = fieldId;
    this.fieldLabel = fieldLabel;
    this.fieldType = fieldType;
    this.fieldValue = fieldValue;
  }

  /**
   * Constructs a <code>RegulatedInformationField</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:ordersV0/js-client.ordersV0.model/RegulatedInformationField} obj Optional instance to populate.
   * @return {module:ordersV0/js-client.ordersV0.model/RegulatedInformationField} The populated <code>RegulatedInformationField</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      switch(typeof data) {
        case 'string':
          obj = String(data);
          break;
        case 'number':
          obj = Number(data);
          break;
        case 'boolean':
          obj = Boolean(data);
          break;
      }
      obj = obj || new RegulatedInformationField();
      if (data.hasOwnProperty('FieldId'))
        obj.fieldId = ApiClient.convertToType(data['FieldId'], 'String');
      if (data.hasOwnProperty('FieldLabel'))
        obj.fieldLabel = ApiClient.convertToType(data['FieldLabel'], 'String');
      if (data.hasOwnProperty('FieldType'))
        obj.fieldType = ApiClient.convertToType(data['FieldType'], 'String');
      if (data.hasOwnProperty('FieldValue'))
        obj.fieldValue = ApiClient.convertToType(data['FieldValue'], 'String');
    }
    return obj;
  }
}

/**
 * The unique identifier of the field.
 * @member {String} fieldId
 */
RegulatedInformationField.prototype.fieldId = undefined;

/**
 * The name of the field.
 * @member {String} fieldLabel
 */
RegulatedInformationField.prototype.fieldLabel = undefined;

/**
 * Allowed values for the <code>fieldType</code> property.
 * @enum {String}
 * @readonly
 */
RegulatedInformationField.FieldTypeEnum = {
  /**
   * value: "Text"
   * @const
   */
  text: "Text",

  /**
   * value: "FileAttachment"
   * @const
   */
  fileAttachment: "FileAttachment"
};

/**
 * The type of field.
 * @member {module:ordersV0/js-client.ordersV0.model/RegulatedInformationField.FieldTypeEnum} fieldType
 */
RegulatedInformationField.prototype.fieldType = undefined;

/**
 * The content of the field as collected in regulatory form. Note that `FileAttachment` type fields contain a URL where you can download the attachment.
 * @member {String} fieldValue
 */
RegulatedInformationField.prototype.fieldValue = undefined;


