/*
 * Selling Partner API for Retail Procurement Shipments
 * The Selling Partner API for Retail Procurement Shipments provides programmatic access to retail shipping data for vendors.
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.29
 *
 * Do not edit the class manually.
 *
 */

import {ApiClient} from '../ApiClient.js';
import {Shipment} from './Shipment.js';

/**
 * The SubmitShipments model module.
 * @module vendorShipments/js-client.vendorShipments.model/SubmitShipments
 * @version v1
 */
export class SubmitShipments {
  /**
   * Constructs a new <code>SubmitShipments</code>.
   * The request schema for the SubmitShipments operation.
   * @alias module:vendorShipments/js-client.vendorShipments.model/SubmitShipments
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>SubmitShipments</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:vendorShipments/js-client.vendorShipments.model/SubmitShipments} obj Optional instance to populate.
   * @return {module:vendorShipments/js-client.vendorShipments.model/SubmitShipments} The populated <code>SubmitShipments</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      switch(typeof data) {
        case 'string':
          obj = String(data);
          break;
        case 'number':
          obj = Number(data);
          break;
        case 'boolean':
          obj = Boolean(data);
          break;
      }
      obj = obj || new SubmitShipments();
      if (data.hasOwnProperty('shipments'))
        obj.shipments = ApiClient.convertToType(data['shipments'], [Shipment]);
    }
    return obj;
  }
}

/**
 * A list of one or more shipments with underlying details.
 * @member {Array.<module:vendorShipments/js-client.vendorShipments.model/Shipment>} shipments
 */
SubmitShipments.prototype.shipments = undefined;


