/*
 * Selling Partner API for Retail Procurement Shipments
 * The Selling Partner API for Retail Procurement Shipments provides programmatic access to retail shipping data for vendors.
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.29
 *
 * Do not edit the class manually.
 *
 */

import {ApiClient} from '../ApiClient.js';

/**
 * The TaxRegistrationDetails model module.
 * @module vendorShipments/js-client.vendorShipments.model/TaxRegistrationDetails
 * @version v1
 */
export class TaxRegistrationDetails {
  /**
   * Constructs a new <code>TaxRegistrationDetails</code>.
   * Tax registration details of the entity.
   * @alias module:vendorShipments/js-client.vendorShipments.model/TaxRegistrationDetails
   * @class
   * @param taxRegistrationType {module:vendorShipments/js-client.vendorShipments.model/TaxRegistrationDetails.TaxRegistrationTypeEnum} Tax registration type for the entity.
   * @param taxRegistrationNumber {String} Tax registration number for the entity. For example, VAT ID.
   */
  constructor(taxRegistrationType, taxRegistrationNumber) {
    this.taxRegistrationType = taxRegistrationType;
    this.taxRegistrationNumber = taxRegistrationNumber;
  }

  /**
   * Constructs a <code>TaxRegistrationDetails</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:vendorShipments/js-client.vendorShipments.model/TaxRegistrationDetails} obj Optional instance to populate.
   * @return {module:vendorShipments/js-client.vendorShipments.model/TaxRegistrationDetails} The populated <code>TaxRegistrationDetails</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      switch(typeof data) {
        case 'string':
          obj = String(data);
          break;
        case 'number':
          obj = Number(data);
          break;
        case 'boolean':
          obj = Boolean(data);
          break;
      }
      obj = obj || new TaxRegistrationDetails();
      if (data.hasOwnProperty('taxRegistrationType'))
        obj.taxRegistrationType = ApiClient.convertToType(data['taxRegistrationType'], 'String');
      if (data.hasOwnProperty('taxRegistrationNumber'))
        obj.taxRegistrationNumber = ApiClient.convertToType(data['taxRegistrationNumber'], 'String');
    }
    return obj;
  }
}

/**
 * Allowed values for the <code>taxRegistrationType</code> property.
 * @enum {String}
 * @readonly
 */
TaxRegistrationDetails.TaxRegistrationTypeEnum = {
  /**
   * value: "VAT"
   * @const
   */
  VAT: "VAT",

  /**
   * value: "GST"
   * @const
   */
  GST: "GST"
};

/**
 * Tax registration type for the entity.
 * @member {module:vendorShipments/js-client.vendorShipments.model/TaxRegistrationDetails.TaxRegistrationTypeEnum} taxRegistrationType
 */
TaxRegistrationDetails.prototype.taxRegistrationType = undefined;

/**
 * Tax registration number for the entity. For example, VAT ID.
 * @member {String} taxRegistrationNumber
 */
TaxRegistrationDetails.prototype.taxRegistrationNumber = undefined;


