/*
 * The Selling Partner API for FBA inbound operations.
 * The Selling Partner API for Fulfillment By Amazon (FBA) Inbound. The FBA Inbound API enables building inbound workflows to create, manage, and send shipments into Amazon's fulfillment network. The API has interoperability with the Send-to-Amazon user interface.
 *
 * OpenAPI spec version: 2024-03-20
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.29
 *
 * Do not edit the class manually.
 *
 */

import {ApiClient} from '../ApiClient.js';

/**
 * The Window model module.
 * @module fulfillmentInbound_2024-03-20/js-client.fulfillmentInbound_2024-03-20.model/Window
 * @version 2024-03-20
 */
export class Window {
  /**
   * Constructs a new <code>Window</code>.
   * Contains a start and end DateTime representing a time range.
   * @alias module:fulfillmentInbound_2024-03-20/js-client.fulfillmentInbound_2024-03-20.model/Window
   * @class
   * @param end {Date} The end timestamp of the window.
   * @param start {Date} The start timestamp of the window.
   */
  constructor(end, start) {
    this.end = end;
    this.start = start;
  }

  /**
   * Constructs a <code>Window</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:fulfillmentInbound_2024-03-20/js-client.fulfillmentInbound_2024-03-20.model/Window} obj Optional instance to populate.
   * @return {module:fulfillmentInbound_2024-03-20/js-client.fulfillmentInbound_2024-03-20.model/Window} The populated <code>Window</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      switch(typeof data) {
        case 'string':
          obj = String(data);
          break;
        case 'number':
          obj = Number(data);
          break;
        case 'boolean':
          obj = Boolean(data);
          break;
      }
      obj = obj || new Window();
      if (data.hasOwnProperty('editableUntil'))
        obj.editableUntil = ApiClient.convertToType(data['editableUntil'], 'Date');
      if (data.hasOwnProperty('end'))
        obj.end = ApiClient.convertToType(data['end'], 'Date');
      if (data.hasOwnProperty('start'))
        obj.start = ApiClient.convertToType(data['start'], 'Date');
    }
    return obj;
  }
}

/**
 * The timestamp at which this Window can no longer be edited.
 * @member {Date} editableUntil
 */
Window.prototype.editableUntil = undefined;

/**
 * The end timestamp of the window.
 * @member {Date} end
 */
Window.prototype.end = undefined;

/**
 * The start timestamp of the window.
 * @member {Date} start
 */
Window.prototype.start = undefined;


