/*
 * Selling Partner API for Merchant Fulfillment
 * The Selling Partner API for Merchant Fulfillment helps you build applications that let sellers purchase shipping for non-Prime and Prime orders using Amazon’s Buy Shipping Services.
 *
 * OpenAPI spec version: v0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.29
 *
 * Do not edit the class manually.
 *
 */

import {ApiClient} from '../ApiClient.js';
import {AdditionalSellerInputs} from './AdditionalSellerInputs.js';

/**
 * The AdditionalSellerInputsList model module.
 * @module merchantFulfillmentV0/js-client.merchantFulfillmentV0.model/AdditionalSellerInputsList
 * @version v0
 */
export class AdditionalSellerInputsList extends Array {
  /**
   * Constructs a new <code>AdditionalSellerInputsList</code>.
   * A list of additional seller input pairs required to purchase shipping.
   * @alias module:merchantFulfillmentV0/js-client.merchantFulfillmentV0.model/AdditionalSellerInputsList
   * @class
   * @extends Array
   */
  constructor() {
    super();
  }

  /**
   * Constructs a <code>AdditionalSellerInputsList</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:merchantFulfillmentV0/js-client.merchantFulfillmentV0.model/AdditionalSellerInputsList} obj Optional instance to populate.
   * @return {module:merchantFulfillmentV0/js-client.merchantFulfillmentV0.model/AdditionalSellerInputsList} The populated <code>AdditionalSellerInputsList</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      switch(typeof data) {
        case 'string':
          obj = String(data);
          break;
        case 'number':
          obj = Number(data);
          break;
        case 'boolean':
          obj = Boolean(data);
          break;
      }
      obj = obj || new AdditionalSellerInputsList();
      ApiClient.constructFromObject(data, obj, 'AdditionalSellerInputs');
    }
    return obj;
  }
}

