/*
 * Selling Partner API for FBA Inventory
 * The Selling Partner API for FBA Inventory lets you programmatically retrieve information about inventory in Amazon's fulfillment network.
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.29
 *
 * Do not edit the class manually.
 *
 */

import {ApiClient} from '../ApiClient.js';
import {ErrorList} from './ErrorList.js';
import {GetInventorySummariesResult} from './GetInventorySummariesResult.js';
import {Pagination} from './Pagination.js';

/**
 * The GetInventorySummariesResponse model module.
 * @module fbaInventory/js-client.fbaInventory.model/GetInventorySummariesResponse
 * @version v1
 */
export class GetInventorySummariesResponse {
  /**
   * Constructs a new <code>GetInventorySummariesResponse</code>.
   * The Response schema.
   * @alias module:fbaInventory/js-client.fbaInventory.model/GetInventorySummariesResponse
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>GetInventorySummariesResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:fbaInventory/js-client.fbaInventory.model/GetInventorySummariesResponse} obj Optional instance to populate.
   * @return {module:fbaInventory/js-client.fbaInventory.model/GetInventorySummariesResponse} The populated <code>GetInventorySummariesResponse</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      switch(typeof data) {
        case 'string':
          obj = String(data);
          break;
        case 'number':
          obj = Number(data);
          break;
        case 'boolean':
          obj = Boolean(data);
          break;
      }
      obj = obj || new GetInventorySummariesResponse();
      if (data.hasOwnProperty('payload'))
        obj.payload = GetInventorySummariesResult.constructFromObject(data['payload']);
      if (data.hasOwnProperty('pagination'))
        obj.pagination = Pagination.constructFromObject(data['pagination']);
      if (data.hasOwnProperty('errors'))
        obj.errors = ErrorList.constructFromObject(data['errors']);
    }
    return obj;
  }
}

/**
 * The payload for the getInventorySummaries operation.
 * @member {module:fbaInventory/js-client.fbaInventory.model/GetInventorySummariesResult} payload
 */
GetInventorySummariesResponse.prototype.payload = undefined;

/**
 * @member {module:fbaInventory/js-client.fbaInventory.model/Pagination} pagination
 */
GetInventorySummariesResponse.prototype.pagination = undefined;

/**
 * One or more unexpected errors occurred during the getInventorySummaries operation.
 * @member {module:fbaInventory/js-client.fbaInventory.model/ErrorList} errors
 */
GetInventorySummariesResponse.prototype.errors = undefined;


