/*
 * Amazon Shipping API
 * The Amazon Shipping API is designed to support outbound shipping use cases both for orders originating on Amazon-owned marketplaces as well as external channels/marketplaces. With these APIs, you can request shipping rates, create shipments, cancel shipments, and track shipments.
 *
 * OpenAPI spec version: v2
 * Contact: swa-api-core@amazon.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.29
 *
 * Do not edit the class manually.
 *
 */

import {ApiClient} from '../ApiClient.js';
import {PackageDocumentDetailList} from './PackageDocumentDetailList.js';
import {Promise} from './Promise.js';
import {ShipmentId} from './ShipmentId.js';

/**
 * The PurchaseShipmentResult model module.
 * @module shippingV2/js-client.shippingV2.model/PurchaseShipmentResult
 * @version v2
 */
export class PurchaseShipmentResult {
  /**
   * Constructs a new <code>PurchaseShipmentResult</code>.
   * The payload for the purchaseShipment operation.
   * @alias module:shippingV2/js-client.shippingV2.model/PurchaseShipmentResult
   * @class
   * @param shipmentId {module:shippingV2/js-client.shippingV2.model/ShipmentId} 
   * @param packageDocumentDetails {module:shippingV2/js-client.shippingV2.model/PackageDocumentDetailList} 
   * @param promise {module:shippingV2/js-client.shippingV2.model/Promise} 
   */
  constructor(shipmentId, packageDocumentDetails, promise) {
    this.shipmentId = shipmentId;
    this.packageDocumentDetails = packageDocumentDetails;
    this.promise = promise;
  }

  /**
   * Constructs a <code>PurchaseShipmentResult</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:shippingV2/js-client.shippingV2.model/PurchaseShipmentResult} obj Optional instance to populate.
   * @return {module:shippingV2/js-client.shippingV2.model/PurchaseShipmentResult} The populated <code>PurchaseShipmentResult</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      switch(typeof data) {
        case 'string':
          obj = String(data);
          break;
        case 'number':
          obj = Number(data);
          break;
        case 'boolean':
          obj = Boolean(data);
          break;
      }
      obj = obj || new PurchaseShipmentResult();
      if (data.hasOwnProperty('shipmentId'))
        obj.shipmentId = ShipmentId.constructFromObject(data['shipmentId']);
      if (data.hasOwnProperty('packageDocumentDetails'))
        obj.packageDocumentDetails = PackageDocumentDetailList.constructFromObject(data['packageDocumentDetails']);
      if (data.hasOwnProperty('promise'))
        obj.promise = Promise.constructFromObject(data['promise']);
    }
    return obj;
  }
}

/**
 * @member {module:shippingV2/js-client.shippingV2.model/ShipmentId} shipmentId
 */
PurchaseShipmentResult.prototype.shipmentId = undefined;

/**
 * @member {module:shippingV2/js-client.shippingV2.model/PackageDocumentDetailList} packageDocumentDetails
 */
PurchaseShipmentResult.prototype.packageDocumentDetails = undefined;

/**
 * @member {module:shippingV2/js-client.shippingV2.model/Promise} promise
 */
PurchaseShipmentResult.prototype.promise = undefined;


