/*
 * Selling Partner API for A+ Content Management
 * With the A+ Content API, you can build applications that help selling partners add rich marketing content to their Amazon product detail pages. A+ content helps selling partners share their brand and product story, which helps buyers make informed purchasing decisions. Selling partners assemble content by choosing from content modules and adding images and text.
 *
 * OpenAPI spec version: 2020-11-01
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.29
 *
 * Do not edit the class manually.
 *
 */

import {ApiClient} from '../ApiClient.js';
import {StandardImageCaptionBlock} from './StandardImageCaptionBlock.js';
import {StandardImageTextBlock} from './StandardImageTextBlock.js';
import {StandardTextBlock} from './StandardTextBlock.js';
import {StandardTextListBlock} from './StandardTextListBlock.js';
import {TextComponent} from './TextComponent.js';

/**
 * The StandardImageSidebarModule model module.
 * @module aplusContent_2020-11-01/js-client.aplusContent_2020-11-01.model/StandardImageSidebarModule
 * @version 2020-11-01
 */
export class StandardImageSidebarModule {
  /**
   * Constructs a new <code>StandardImageSidebarModule</code>.
   * Two images, two paragraphs, and two bulleted lists. One image is smaller and displayed in the sidebar.
   * @alias module:aplusContent_2020-11-01/js-client.aplusContent_2020-11-01.model/StandardImageSidebarModule
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>StandardImageSidebarModule</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:aplusContent_2020-11-01/js-client.aplusContent_2020-11-01.model/StandardImageSidebarModule} obj Optional instance to populate.
   * @return {module:aplusContent_2020-11-01/js-client.aplusContent_2020-11-01.model/StandardImageSidebarModule} The populated <code>StandardImageSidebarModule</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      switch(typeof data) {
        case 'string':
          obj = String(data);
          break;
        case 'number':
          obj = Number(data);
          break;
        case 'boolean':
          obj = Boolean(data);
          break;
      }
      obj = obj || new StandardImageSidebarModule();
      if (data.hasOwnProperty('headline'))
        obj.headline = TextComponent.constructFromObject(data['headline']);
      if (data.hasOwnProperty('imageCaptionBlock'))
        obj.imageCaptionBlock = StandardImageCaptionBlock.constructFromObject(data['imageCaptionBlock']);
      if (data.hasOwnProperty('descriptionTextBlock'))
        obj.descriptionTextBlock = StandardTextBlock.constructFromObject(data['descriptionTextBlock']);
      if (data.hasOwnProperty('descriptionListBlock'))
        obj.descriptionListBlock = StandardTextListBlock.constructFromObject(data['descriptionListBlock']);
      if (data.hasOwnProperty('sidebarImageTextBlock'))
        obj.sidebarImageTextBlock = StandardImageTextBlock.constructFromObject(data['sidebarImageTextBlock']);
      if (data.hasOwnProperty('sidebarListBlock'))
        obj.sidebarListBlock = StandardTextListBlock.constructFromObject(data['sidebarListBlock']);
    }
    return obj;
  }
}

/**
 * @member {module:aplusContent_2020-11-01/js-client.aplusContent_2020-11-01.model/TextComponent} headline
 */
StandardImageSidebarModule.prototype.headline = undefined;

/**
 * @member {module:aplusContent_2020-11-01/js-client.aplusContent_2020-11-01.model/StandardImageCaptionBlock} imageCaptionBlock
 */
StandardImageSidebarModule.prototype.imageCaptionBlock = undefined;

/**
 * @member {module:aplusContent_2020-11-01/js-client.aplusContent_2020-11-01.model/StandardTextBlock} descriptionTextBlock
 */
StandardImageSidebarModule.prototype.descriptionTextBlock = undefined;

/**
 * @member {module:aplusContent_2020-11-01/js-client.aplusContent_2020-11-01.model/StandardTextListBlock} descriptionListBlock
 */
StandardImageSidebarModule.prototype.descriptionListBlock = undefined;

/**
 * @member {module:aplusContent_2020-11-01/js-client.aplusContent_2020-11-01.model/StandardImageTextBlock} sidebarImageTextBlock
 */
StandardImageSidebarModule.prototype.sidebarImageTextBlock = undefined;

/**
 * @member {module:aplusContent_2020-11-01/js-client.aplusContent_2020-11-01.model/StandardTextListBlock} sidebarListBlock
 */
StandardImageSidebarModule.prototype.sidebarListBlock = undefined;


