/*
 * Selling Partner API for Direct Fulfillment Shipping
 * The Selling Partner API for Direct Fulfillment Shipping provides programmatic access to a direct fulfillment vendor's shipping data.
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.29
 *
 * Do not edit the class manually.
 *
 */

import {ApiClient} from '../ApiClient.js';

/**
 * The StatusUpdateDetailsShipmentSchedule model module.
 * @module vendorDirectFulfillmentShippingV1/js-client.vendorDirectFulfillmentShippingV1.model/StatusUpdateDetailsShipmentSchedule
 * @version v1
 */
export class StatusUpdateDetailsShipmentSchedule {
  /**
   * Constructs a new <code>StatusUpdateDetailsShipmentSchedule</code>.
   * Details for the scheduled delivery timeline for a shipment, including the estimated delivery date and time, as well as the start and end times of the appointment window for delivery.
   * @alias module:vendorDirectFulfillmentShippingV1/js-client.vendorDirectFulfillmentShippingV1.model/StatusUpdateDetailsShipmentSchedule
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>StatusUpdateDetailsShipmentSchedule</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:vendorDirectFulfillmentShippingV1/js-client.vendorDirectFulfillmentShippingV1.model/StatusUpdateDetailsShipmentSchedule} obj Optional instance to populate.
   * @return {module:vendorDirectFulfillmentShippingV1/js-client.vendorDirectFulfillmentShippingV1.model/StatusUpdateDetailsShipmentSchedule} The populated <code>StatusUpdateDetailsShipmentSchedule</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      switch(typeof data) {
        case 'string':
          obj = String(data);
          break;
        case 'number':
          obj = Number(data);
          break;
        case 'boolean':
          obj = Boolean(data);
          break;
      }
      obj = obj || new StatusUpdateDetailsShipmentSchedule();
      if (data.hasOwnProperty('estimatedDeliveryDateTime'))
        obj.estimatedDeliveryDateTime = ApiClient.convertToType(data['estimatedDeliveryDateTime'], 'Date');
      if (data.hasOwnProperty('apptWindowStartDateTime'))
        obj.apptWindowStartDateTime = ApiClient.convertToType(data['apptWindowStartDateTime'], 'Date');
      if (data.hasOwnProperty('apptWindowEndDateTime'))
        obj.apptWindowEndDateTime = ApiClient.convertToType(data['apptWindowEndDateTime'], 'Date');
    }
    return obj;
  }
}

/**
 * Date on which the shipment is expected to reach the customer delivery location. This field is expected to be in <a href='https://developer-docs.amazon.com/sp-api/docs/iso-8601'>ISO 8601</a> date/time format, with UTC time zone or UTC offset. For example, `2020-07-16T23:00:00Z` or `2020-07-16T23:00:00+01:00`.
 * @member {Date} estimatedDeliveryDateTime
 */
StatusUpdateDetailsShipmentSchedule.prototype.estimatedDeliveryDateTime = undefined;

/**
 * This field indicates the date and time at the start of the appointment window scheduled to deliver the shipment. This field is expected to be in <a href='https://developer-docs.amazon.com/sp-api/docs/iso-8601'>ISO 8601</a> date/time format, with UTC time zone or UTC offset. For example, `2020-07-16T23:00:00Z` or `2020-07-16T23:00:00+01:00`.
 * @member {Date} apptWindowStartDateTime
 */
StatusUpdateDetailsShipmentSchedule.prototype.apptWindowStartDateTime = undefined;

/**
 * This field indicates the date and time at the end of the appointment window scheduled to deliver the shipment. This field is expected to be in <a href='https://developer-docs.amazon.com/sp-api/docs/iso-8601'>ISO 8601</a> date/time format, with UTC time zone or UTC offset. For example, `2020-07-16T23:00:00Z` or `2020-07-16T23:00:00+01:00`.
 * @member {Date} apptWindowEndDateTime
 */
StatusUpdateDetailsShipmentSchedule.prototype.apptWindowEndDateTime = undefined;


