/*
 * Selling Partner APIs for Fulfillment Outbound
 * The Selling Partner API for Fulfillment Outbound lets you create applications that help a seller fulfill Multi-Channel Fulfillment orders using their inventory in Amazon's fulfillment network. You can get information on both potential and existing fulfillment orders.
 *
 * OpenAPI spec version: 2020-07-01
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.29
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../../src/fulfillmentOutbound_2020-07-01/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../../src/fulfillmentOutbound_2020-07-01/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SellingPartnerApisForFulfillmentOutbound);
  }
}(this, function(expect, SellingPartnerApisForFulfillmentOutbound) {
  'use strict';

  var instance;

  describe('fulfillmentOutbound_2020-07-01', function() {
    describe('ReturnItem', function() {
      beforeEach(function() {
        instance = new SellingPartnerApisForFulfillmentOutbound.ReturnItem();
      });

      it('should create an instance of ReturnItem', function() {
        // TODO: update the code to test ReturnItem
        expect(instance).to.be.a(SellingPartnerApisForFulfillmentOutbound.ReturnItem);
      });

      it('should have the property sellerReturnItemId (base name: "sellerReturnItemId")', function() {
        // TODO: update the code to test the property sellerReturnItemId
        expect(instance).to.have.property('sellerReturnItemId');
        // expect(instance.sellerReturnItemId).to.be(expectedValueLiteral);
      });

      it('should have the property sellerFulfillmentOrderItemId (base name: "sellerFulfillmentOrderItemId")', function() {
        // TODO: update the code to test the property sellerFulfillmentOrderItemId
        expect(instance).to.have.property('sellerFulfillmentOrderItemId');
        // expect(instance.sellerFulfillmentOrderItemId).to.be(expectedValueLiteral);
      });

      it('should have the property amazonShipmentId (base name: "amazonShipmentId")', function() {
        // TODO: update the code to test the property amazonShipmentId
        expect(instance).to.have.property('amazonShipmentId');
        // expect(instance.amazonShipmentId).to.be(expectedValueLiteral);
      });

      it('should have the property sellerReturnReasonCode (base name: "sellerReturnReasonCode")', function() {
        // TODO: update the code to test the property sellerReturnReasonCode
        expect(instance).to.have.property('sellerReturnReasonCode');
        // expect(instance.sellerReturnReasonCode).to.be(expectedValueLiteral);
      });

      it('should have the property returnComment (base name: "returnComment")', function() {
        // TODO: update the code to test the property returnComment
        expect(instance).to.have.property('returnComment');
        // expect(instance.returnComment).to.be(expectedValueLiteral);
      });

      it('should have the property amazonReturnReasonCode (base name: "amazonReturnReasonCode")', function() {
        // TODO: update the code to test the property amazonReturnReasonCode
        expect(instance).to.have.property('amazonReturnReasonCode');
        // expect(instance.amazonReturnReasonCode).to.be(expectedValueLiteral);
      });

      it('should have the property status (base name: "status")', function() {
        // TODO: update the code to test the property status
        expect(instance).to.have.property('status');
        // expect(instance.status).to.be(expectedValueLiteral);
      });

      it('should have the property statusChangedDate (base name: "statusChangedDate")', function() {
        // TODO: update the code to test the property statusChangedDate
        expect(instance).to.have.property('statusChangedDate');
        // expect(instance.statusChangedDate).to.be(expectedValueLiteral);
      });

      it('should have the property returnAuthorizationId (base name: "returnAuthorizationId")', function() {
        // TODO: update the code to test the property returnAuthorizationId
        expect(instance).to.have.property('returnAuthorizationId');
        // expect(instance.returnAuthorizationId).to.be(expectedValueLiteral);
      });

      it('should have the property returnReceivedCondition (base name: "returnReceivedCondition")', function() {
        // TODO: update the code to test the property returnReceivedCondition
        expect(instance).to.have.property('returnReceivedCondition');
        // expect(instance.returnReceivedCondition).to.be(expectedValueLiteral);
      });

      it('should have the property fulfillmentCenterId (base name: "fulfillmentCenterId")', function() {
        // TODO: update the code to test the property fulfillmentCenterId
        expect(instance).to.have.property('fulfillmentCenterId');
        // expect(instance.fulfillmentCenterId).to.be(expectedValueLiteral);
      });

    });
  });

}));
