/*
 * Selling Partner API for Services
 * With the Services API, you can build applications that help service providers get and modify their service orders and manage their resources.
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.29
 *
 * Do not edit the class manually.
 *
 */

import {ApiClient} from '../ApiClient.js';
import {AppointmentId} from './AppointmentId.js';
import {AppointmentTime} from './AppointmentTime.js';
import {Poa} from './Poa.js';
import {Technician} from './Technician.js';

/**
 * The Appointment model module.
 * @module services/js-client.services.model/Appointment
 * @version v1
 */
export class Appointment {
  /**
   * Constructs a new <code>Appointment</code>.
   * The details of an appointment.
   * @alias module:services/js-client.services.model/Appointment
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>Appointment</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:services/js-client.services.model/Appointment} obj Optional instance to populate.
   * @return {module:services/js-client.services.model/Appointment} The populated <code>Appointment</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      switch(typeof data) {
        case 'string':
          obj = String(data);
          break;
        case 'number':
          obj = Number(data);
          break;
        case 'boolean':
          obj = Boolean(data);
          break;
      }
      obj = obj || new Appointment();
      if (data.hasOwnProperty('appointmentId'))
        obj.appointmentId = AppointmentId.constructFromObject(data['appointmentId']);
      if (data.hasOwnProperty('appointmentStatus'))
        obj.appointmentStatus = ApiClient.convertToType(data['appointmentStatus'], 'String');
      if (data.hasOwnProperty('appointmentTime'))
        obj.appointmentTime = AppointmentTime.constructFromObject(data['appointmentTime']);
      if (data.hasOwnProperty('assignedTechnicians'))
        obj.assignedTechnicians = ApiClient.convertToType(data['assignedTechnicians'], [Technician]);
      if (data.hasOwnProperty('rescheduledAppointmentId'))
        obj.rescheduledAppointmentId = AppointmentId.constructFromObject(data['rescheduledAppointmentId']);
      if (data.hasOwnProperty('poa'))
        obj.poa = Poa.constructFromObject(data['poa']);
    }
    return obj;
  }
}

/**
 * The appointment identifier.
 * @member {module:services/js-client.services.model/AppointmentId} appointmentId
 */
Appointment.prototype.appointmentId = undefined;

/**
 * Allowed values for the <code>appointmentStatus</code> property.
 * @enum {String}
 * @readonly
 */
Appointment.AppointmentStatusEnum = {
  /**
   * value: "ACTIVE"
   * @const
   */
  ACTIVE: "ACTIVE",

  /**
   * value: "CANCELLED"
   * @const
   */
  CANCELLED: "CANCELLED",

  /**
   * value: "COMPLETED"
   * @const
   */
  COMPLETED: "COMPLETED"
};

/**
 * The status of the appointment.
 * @member {module:services/js-client.services.model/Appointment.AppointmentStatusEnum} appointmentStatus
 */
Appointment.prototype.appointmentStatus = undefined;

/**
 * The time of the appointment window.
 * @member {module:services/js-client.services.model/AppointmentTime} appointmentTime
 */
Appointment.prototype.appointmentTime = undefined;

/**
 * A list of technicians assigned to the service job.
 * @member {Array.<module:services/js-client.services.model/Technician>} assignedTechnicians
 */
Appointment.prototype.assignedTechnicians = undefined;

/**
 * The identifier of a rescheduled appointment.
 * @member {module:services/js-client.services.model/AppointmentId} rescheduledAppointmentId
 */
Appointment.prototype.rescheduledAppointmentId = undefined;

/**
 * Proof of Appointment (POA) details.
 * @member {module:services/js-client.services.model/Poa} poa
 */
Appointment.prototype.poa = undefined;


