/*
 * Selling Partner API for Services
 * With the Services API, you can build applications that help service providers get and modify their service orders and manage their resources.
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.29
 *
 * Do not edit the class manually.
 *
 */

import {ApiClient} from '../ApiClient.js';

/**
 * The RangeSlot model module.
 * @module services/js-client.services.model/RangeSlot
 * @version v1
 */
export class RangeSlot {
  /**
   * Constructs a new <code>RangeSlot</code>.
   * Capacity slots represented in a format similar to availability rules.
   * @alias module:services/js-client.services.model/RangeSlot
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>RangeSlot</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:services/js-client.services.model/RangeSlot} obj Optional instance to populate.
   * @return {module:services/js-client.services.model/RangeSlot} The populated <code>RangeSlot</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      switch(typeof data) {
        case 'string':
          obj = String(data);
          break;
        case 'number':
          obj = Number(data);
          break;
        case 'boolean':
          obj = Boolean(data);
          break;
      }
      obj = obj || new RangeSlot();
      if (data.hasOwnProperty('startDateTime'))
        obj.startDateTime = ApiClient.convertToType(data['startDateTime'], 'Date');
      if (data.hasOwnProperty('endDateTime'))
        obj.endDateTime = ApiClient.convertToType(data['endDateTime'], 'Date');
      if (data.hasOwnProperty('capacity'))
        obj.capacity = ApiClient.convertToType(data['capacity'], 'Number');
    }
    return obj;
  }
}

/**
 * Start date time of slot in ISO 8601 format with precision of seconds.
 * @member {Date} startDateTime
 */
RangeSlot.prototype.startDateTime = undefined;

/**
 * End date time of slot in ISO 8601 format with precision of seconds.
 * @member {Date} endDateTime
 */
RangeSlot.prototype.endDateTime = undefined;

/**
 * Capacity of the slot.
 * @member {Number} capacity
 */
RangeSlot.prototype.capacity = undefined;


