/*
 * Selling Partner API for Services
 * With the Services API, you can build applications that help service providers get and modify their service orders and manage their resources.
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.29
 *
 * Do not edit the class manually.
 *
 */

import {ApiClient} from '../ApiClient.js';
import {RangeCapacity} from './RangeCapacity.js';

/**
 * The RangeSlotCapacity model module.
 * @module services/js-client.services.model/RangeSlotCapacity
 * @version v1
 */
export class RangeSlotCapacity {
  /**
   * Constructs a new <code>RangeSlotCapacity</code>.
   * Response schema for the `getRangeSlotCapacity` operation.
   * @alias module:services/js-client.services.model/RangeSlotCapacity
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>RangeSlotCapacity</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:services/js-client.services.model/RangeSlotCapacity} obj Optional instance to populate.
   * @return {module:services/js-client.services.model/RangeSlotCapacity} The populated <code>RangeSlotCapacity</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      switch(typeof data) {
        case 'string':
          obj = String(data);
          break;
        case 'number':
          obj = Number(data);
          break;
        case 'boolean':
          obj = Boolean(data);
          break;
      }
      obj = obj || new RangeSlotCapacity();
      if (data.hasOwnProperty('resourceId'))
        obj.resourceId = ApiClient.convertToType(data['resourceId'], 'String');
      if (data.hasOwnProperty('capacities'))
        obj.capacities = ApiClient.convertToType(data['capacities'], [RangeCapacity]);
      if (data.hasOwnProperty('nextPageToken'))
        obj.nextPageToken = ApiClient.convertToType(data['nextPageToken'], 'String');
    }
    return obj;
  }
}

/**
 * Resource Identifier.
 * @member {String} resourceId
 */
RangeSlotCapacity.prototype.resourceId = undefined;

/**
 * Array of range capacities where each entry is for a specific capacity type.
 * @member {Array.<module:services/js-client.services.model/RangeCapacity>} capacities
 */
RangeSlotCapacity.prototype.capacities = undefined;

/**
 * Next page token, if there are more pages.
 * @member {String} nextPageToken
 */
RangeSlotCapacity.prototype.nextPageToken = undefined;


