/*
 * Selling Partner API for Supply Sources
 * Manage configurations and capabilities of seller supply sources.
 *
 * OpenAPI spec version: 2020-07-01
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.29
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../../src/supplySources_2020-07-01/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../../src/supplySources_2020-07-01/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SellingPartnerApiForSupplySources);
  }
}(this, function(expect, SellingPartnerApiForSupplySources) {
  'use strict';

  var instance;

  describe('supplySources_2020-07-01', function() {
    describe('ParkingConfiguration', function() {
      beforeEach(function() {
        instance = new SellingPartnerApiForSupplySources.ParkingConfiguration();
      });

      it('should create an instance of ParkingConfiguration', function() {
        // TODO: update the code to test ParkingConfiguration
        expect(instance).to.be.a(SellingPartnerApiForSupplySources.ParkingConfiguration);
      });

      it('should have the property parkingCostType (base name: "parkingCostType")', function() {
        // TODO: update the code to test the property parkingCostType
        expect(instance).to.have.property('parkingCostType');
        // expect(instance.parkingCostType).to.be(expectedValueLiteral);
      });

      it('should have the property parkingSpotIdentificationType (base name: "parkingSpotIdentificationType")', function() {
        // TODO: update the code to test the property parkingSpotIdentificationType
        expect(instance).to.have.property('parkingSpotIdentificationType');
        // expect(instance.parkingSpotIdentificationType).to.be(expectedValueLiteral);
      });

      it('should have the property numberOfParkingSpots (base name: "numberOfParkingSpots")', function() {
        // TODO: update the code to test the property numberOfParkingSpots
        expect(instance).to.have.property('numberOfParkingSpots');
        // expect(instance.numberOfParkingSpots).to.be(expectedValueLiteral);
      });

    });
  });

}));
