/*
 * Selling Partner API for Sellers
 * The [Selling Partner API for Sellers](https://developer-docs.amazon.com/sp-api/docs/sellers-api-v1-reference) (Sellers API) provides essential information about seller accounts, such as:  - The marketplaces a seller can list in - The default language and currency of a marketplace - Whether the seller has suspended listings  Refer to the [Sellers API reference](https://developer-docs.amazon.com/sp-api/docs/sellers-api-v1-reference) for details about this API's operations, data types, and schemas.
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.29
 *
 * Do not edit the class manually.
 *
 */

import {ApiClient} from '../ApiClient.js';

/**
 * The Participation model module.
 * @module sellers/js-client.sellers.model/Participation
 * @version v1
 */
export class Participation {
  /**
   * Constructs a new <code>Participation</code>.
   * Information that is specific to a seller in a marketplace.
   * @alias module:sellers/js-client.sellers.model/Participation
   * @class
   * @param isParticipating {Boolean} If `true`, the seller participates in the marketplace. Otherwise `false`.
   * @param hasSuspendedListings {Boolean} Specifies if the seller has suspended listings. `true` if the seller Listing Status is set to Inactive, otherwise `false`.
   */
  constructor(isParticipating, hasSuspendedListings) {
    this.isParticipating = isParticipating;
    this.hasSuspendedListings = hasSuspendedListings;
  }

  /**
   * Constructs a <code>Participation</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:sellers/js-client.sellers.model/Participation} obj Optional instance to populate.
   * @return {module:sellers/js-client.sellers.model/Participation} The populated <code>Participation</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      switch(typeof data) {
        case 'string':
          obj = String(data);
          break;
        case 'number':
          obj = Number(data);
          break;
        case 'boolean':
          obj = Boolean(data);
          break;
      }
      obj = obj || new Participation();
      if (data.hasOwnProperty('isParticipating'))
        obj.isParticipating = ApiClient.convertToType(data['isParticipating'], 'Boolean');
      if (data.hasOwnProperty('hasSuspendedListings'))
        obj.hasSuspendedListings = ApiClient.convertToType(data['hasSuspendedListings'], 'Boolean');
    }
    return obj;
  }
}

/**
 * If `true`, the seller participates in the marketplace. Otherwise `false`.
 * @member {Boolean} isParticipating
 */
Participation.prototype.isParticipating = undefined;

/**
 * Specifies if the seller has suspended listings. `true` if the seller Listing Status is set to Inactive, otherwise `false`.
 * @member {Boolean} hasSuspendedListings
 */
Participation.prototype.hasSuspendedListings = undefined;


