/*
 * Selling Partner API for Reports
 * The Selling Partner API for Reports lets you retrieve and manage a variety of reports that can help selling partners manage their businesses.
 *
 * OpenAPI spec version: 2021-06-30
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.29
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../../src/reports_2021-06-30/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../../src/reports_2021-06-30/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SellingPartnerApiForReports);
  }
}(this, function(expect, SellingPartnerApiForReports) {
  'use strict';

  var instance;

  describe('reports_2021-06-30', function() {
    describe('GetReportsResponse', function() {
      beforeEach(function() {
        instance = new SellingPartnerApiForReports.GetReportsResponse();
      });

      it('should create an instance of GetReportsResponse', function() {
        // TODO: update the code to test GetReportsResponse
        expect(instance).to.be.a(SellingPartnerApiForReports.GetReportsResponse);
      });

      it('should have the property reports (base name: "reports")', function() {
        // TODO: update the code to test the property reports
        expect(instance).to.have.property('reports');
        // expect(instance.reports).to.be(expectedValueLiteral);
      });

      it('should have the property nextToken (base name: "nextToken")', function() {
        // TODO: update the code to test the property nextToken
        expect(instance).to.have.property('nextToken');
        // expect(instance.nextToken).to.be(expectedValueLiteral);
      });

    });
  });

}));
