/*
 * Selling Partner API for Reports
 * The Selling Partner API for Reports lets you retrieve and manage a variety of reports that can help selling partners manage their businesses.
 *
 * OpenAPI spec version: 2021-06-30
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.29
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../../src/reports_2021-06-30/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../../src/reports_2021-06-30/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SellingPartnerApiForReports);
  }
}(this, function(expect, SellingPartnerApiForReports) {
  'use strict';

  var instance;

  describe('reports_2021-06-30', function() {
    describe('ReportDocument', function() {
      beforeEach(function() {
        instance = new SellingPartnerApiForReports.ReportDocument();
      });

      it('should create an instance of ReportDocument', function() {
        // TODO: update the code to test ReportDocument
        expect(instance).to.be.a(SellingPartnerApiForReports.ReportDocument);
      });

      it('should have the property reportDocumentId (base name: "reportDocumentId")', function() {
        // TODO: update the code to test the property reportDocumentId
        expect(instance).to.have.property('reportDocumentId');
        // expect(instance.reportDocumentId).to.be(expectedValueLiteral);
      });

      it('should have the property url (base name: "url")', function() {
        // TODO: update the code to test the property url
        expect(instance).to.have.property('url');
        // expect(instance.url).to.be(expectedValueLiteral);
      });

      it('should have the property compressionAlgorithm (base name: "compressionAlgorithm")', function() {
        // TODO: update the code to test the property compressionAlgorithm
        expect(instance).to.have.property('compressionAlgorithm');
        // expect(instance.compressionAlgorithm).to.be(expectedValueLiteral);
      });

    });
  });

}));
