/*
 * Selling Partner API for Pricing
 * The Selling Partner API for Pricing helps you programmatically retrieve product pricing and offer information for Amazon Marketplace products.
 *
 * OpenAPI spec version: v0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.29
 *
 * Do not edit the class manually.
 *
 */

import {ApiClient} from '../ApiClient.js';
import {MoneyType} from './MoneyType.js';
import {OfferCustomerType} from './OfferCustomerType.js';
import {Points} from './Points.js';
import {QuantityDiscountType} from './QuantityDiscountType.js';

/**
 * The LowestPriceType model module.
 * @module productPricingV0/js-client.productPricingV0.model/LowestPriceType
 * @version v0
 */
export class LowestPriceType {
  /**
   * Constructs a new <code>LowestPriceType</code>.
   * @alias module:productPricingV0/js-client.productPricingV0.model/LowestPriceType
   * @class
   * @param condition {String} Indicates the condition of the item. For example: New, Used, Collectible, Refurbished, or Club.
   * @param fulfillmentChannel {String} Indicates whether the item is fulfilled by Amazon or by the seller.
   * @param listingPrice {module:productPricingV0/js-client.productPricingV0.model/MoneyType} The price of the item.
   */
  constructor(condition, fulfillmentChannel, listingPrice) {
    this.condition = condition;
    this.fulfillmentChannel = fulfillmentChannel;
    this.listingPrice = listingPrice;
  }

  /**
   * Constructs a <code>LowestPriceType</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:productPricingV0/js-client.productPricingV0.model/LowestPriceType} obj Optional instance to populate.
   * @return {module:productPricingV0/js-client.productPricingV0.model/LowestPriceType} The populated <code>LowestPriceType</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      switch(typeof data) {
        case 'string':
          obj = String(data);
          break;
        case 'number':
          obj = Number(data);
          break;
        case 'boolean':
          obj = Boolean(data);
          break;
      }
      obj = obj || new LowestPriceType();
      if (data.hasOwnProperty('condition'))
        obj.condition = ApiClient.convertToType(data['condition'], 'String');
      if (data.hasOwnProperty('fulfillmentChannel'))
        obj.fulfillmentChannel = ApiClient.convertToType(data['fulfillmentChannel'], 'String');
      if (data.hasOwnProperty('offerType'))
        obj.offerType = OfferCustomerType.constructFromObject(data['offerType']);
      if (data.hasOwnProperty('quantityTier'))
        obj.quantityTier = ApiClient.convertToType(data['quantityTier'], 'Number');
      if (data.hasOwnProperty('quantityDiscountType'))
        obj.quantityDiscountType = QuantityDiscountType.constructFromObject(data['quantityDiscountType']);
      if (data.hasOwnProperty('LandedPrice'))
        obj.landedPrice = MoneyType.constructFromObject(data['LandedPrice']);
      if (data.hasOwnProperty('ListingPrice'))
        obj.listingPrice = MoneyType.constructFromObject(data['ListingPrice']);
      if (data.hasOwnProperty('Shipping'))
        obj.shipping = MoneyType.constructFromObject(data['Shipping']);
      if (data.hasOwnProperty('Points'))
        obj.points = Points.constructFromObject(data['Points']);
    }
    return obj;
  }
}

/**
 * Indicates the condition of the item. For example: New, Used, Collectible, Refurbished, or Club.
 * @member {String} condition
 */
LowestPriceType.prototype.condition = undefined;

/**
 * Indicates whether the item is fulfilled by Amazon or by the seller.
 * @member {String} fulfillmentChannel
 */
LowestPriceType.prototype.fulfillmentChannel = undefined;

/**
 * Indicates the type of customer that the offer is valid for.
 * @member {module:productPricingV0/js-client.productPricingV0.model/OfferCustomerType} offerType
 */
LowestPriceType.prototype.offerType = undefined;

/**
 * Indicates at what quantity this price becomes active.
 * @member {Number} quantityTier
 */
LowestPriceType.prototype.quantityTier = undefined;

/**
 * Indicates the type of quantity discount this price applies to.
 * @member {module:productPricingV0/js-client.productPricingV0.model/QuantityDiscountType} quantityDiscountType
 */
LowestPriceType.prototype.quantityDiscountType = undefined;

/**
 * The value calculated by adding ListingPrice + Shipping - Points.
 * @member {module:productPricingV0/js-client.productPricingV0.model/MoneyType} landedPrice
 */
LowestPriceType.prototype.landedPrice = undefined;

/**
 * The price of the item.
 * @member {module:productPricingV0/js-client.productPricingV0.model/MoneyType} listingPrice
 */
LowestPriceType.prototype.listingPrice = undefined;

/**
 * The shipping cost.
 * @member {module:productPricingV0/js-client.productPricingV0.model/MoneyType} shipping
 */
LowestPriceType.prototype.shipping = undefined;

/**
 * The number of Amazon Points offered with the purchase of an item.
 * @member {module:productPricingV0/js-client.productPricingV0.model/Points} points
 */
LowestPriceType.prototype.points = undefined;


