/*
 * Amazon Shipping API
 * The Amazon Shipping API is designed to support outbound shipping use cases both for orders originating on Amazon-owned marketplaces as well as external channels/marketplaces. With these APIs, you can request shipping rates, create shipments, cancel shipments, and track shipments.
 *
 * OpenAPI spec version: v2
 * Contact: swa-api-core@amazon.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.29
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../../src/shippingV2/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../../src/shippingV2/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.AmazonShippingApi);
  }
}(this, function(expect, AmazonShippingApi) {
  'use strict';

  var instance;

  describe('shippingV2', function() {
    describe('CarrierAccountAttribute', function() {
      beforeEach(function() {
        instance = new AmazonShippingApi.CarrierAccountAttribute();
      });

      it('should create an instance of CarrierAccountAttribute', function() {
        // TODO: update the code to test CarrierAccountAttribute
        expect(instance).to.be.a(AmazonShippingApi.CarrierAccountAttribute);
      });

      it('should have the property attributeName (base name: "attributeName")', function() {
        // TODO: update the code to test the property attributeName
        expect(instance).to.have.property('attributeName');
        // expect(instance.attributeName).to.be(expectedValueLiteral);
      });

      it('should have the property propertyGroup (base name: "propertyGroup")', function() {
        // TODO: update the code to test the property propertyGroup
        expect(instance).to.have.property('propertyGroup');
        // expect(instance.propertyGroup).to.be(expectedValueLiteral);
      });

      it('should have the property value (base name: "value")', function() {
        // TODO: update the code to test the property value
        expect(instance).to.have.property('value');
        // expect(instance.value).to.be(expectedValueLiteral);
      });

    });
  });

}));
