/*
 * Selling Partner API for Feeds
 * Effective **June 27, 2024**, the Selling Partner API for Feeds v2020-09-04 will no longer be available and all calls to it will fail. Integrations that rely on the Feeds API must migrate to [Feeds v2021-06-30](https://developer-docs.amazon.com/sp-api/docs/feeds-api-v2021-06-30-reference) to avoid service disruption.
 *
 * OpenAPI spec version: 2020-09-04
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.29
 *
 * Do not edit the class manually.
 *
 */

import {ApiClient} from '../ApiClient.js';

/**
 * The CreateFeedResult model module.
 * @module feeds_2020-09-04/js-client.feeds_2020-09-04.model/CreateFeedResult
 * @version 2020-09-04
 */
export class CreateFeedResult {
  /**
   * Constructs a new <code>CreateFeedResult</code>.
   * @alias module:feeds_2020-09-04/js-client.feeds_2020-09-04.model/CreateFeedResult
   * @class
   * @param feedId {String} The identifier for the feed. This identifier is unique only in combination with a seller ID.
   */
  constructor(feedId) {
    this.feedId = feedId;
  }

  /**
   * Constructs a <code>CreateFeedResult</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:feeds_2020-09-04/js-client.feeds_2020-09-04.model/CreateFeedResult} obj Optional instance to populate.
   * @return {module:feeds_2020-09-04/js-client.feeds_2020-09-04.model/CreateFeedResult} The populated <code>CreateFeedResult</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      switch(typeof data) {
        case 'string':
          obj = String(data);
          break;
        case 'number':
          obj = Number(data);
          break;
        case 'boolean':
          obj = Boolean(data);
          break;
      }
      obj = obj || new CreateFeedResult();
      if (data.hasOwnProperty('feedId'))
        obj.feedId = ApiClient.convertToType(data['feedId'], 'String');
    }
    return obj;
  }
}

/**
 * The identifier for the feed. This identifier is unique only in combination with a seller ID.
 * @member {String} feedId
 */
CreateFeedResult.prototype.feedId = undefined;


