/*
 * Selling Partner API for Finances
 * The Selling Partner API for Finances provides financial information that is relevant to a seller's business. You can obtain financial events for a given order, financial event group, or date range without having to wait until a statement period closes. You can also obtain financial event groups for a given date range. 
 *
 * OpenAPI spec version: v0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.29
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../../src/financesV0/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../../src/financesV0/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SellingPartnerApiForFinances);
  }
}(this, function(expect, SellingPartnerApiForFinances) {
  'use strict';

  var instance;

  describe('financesV0', function() {
    describe('AffordabilityExpenseEvent', function() {
      beforeEach(function() {
        instance = new SellingPartnerApiForFinances.AffordabilityExpenseEvent();
      });

      it('should create an instance of AffordabilityExpenseEvent', function() {
        // TODO: update the code to test AffordabilityExpenseEvent
        expect(instance).to.be.a(SellingPartnerApiForFinances.AffordabilityExpenseEvent);
      });

      it('should have the property amazonOrderId (base name: "AmazonOrderId")', function() {
        // TODO: update the code to test the property amazonOrderId
        expect(instance).to.have.property('amazonOrderId');
        // expect(instance.amazonOrderId).to.be(expectedValueLiteral);
      });

      it('should have the property postedDate (base name: "PostedDate")', function() {
        // TODO: update the code to test the property postedDate
        expect(instance).to.have.property('postedDate');
        // expect(instance.postedDate).to.be(expectedValueLiteral);
      });

      it('should have the property marketplaceId (base name: "MarketplaceId")', function() {
        // TODO: update the code to test the property marketplaceId
        expect(instance).to.have.property('marketplaceId');
        // expect(instance.marketplaceId).to.be(expectedValueLiteral);
      });

      it('should have the property transactionType (base name: "TransactionType")', function() {
        // TODO: update the code to test the property transactionType
        expect(instance).to.have.property('transactionType');
        // expect(instance.transactionType).to.be(expectedValueLiteral);
      });

      it('should have the property baseExpense (base name: "BaseExpense")', function() {
        // TODO: update the code to test the property baseExpense
        expect(instance).to.have.property('baseExpense');
        // expect(instance.baseExpense).to.be(expectedValueLiteral);
      });

      it('should have the property taxTypeCGST (base name: "TaxTypeCGST")', function() {
        // TODO: update the code to test the property taxTypeCGST
        expect(instance).to.have.property('taxTypeCGST');
        // expect(instance.taxTypeCGST).to.be(expectedValueLiteral);
      });

      it('should have the property taxTypeSGST (base name: "TaxTypeSGST")', function() {
        // TODO: update the code to test the property taxTypeSGST
        expect(instance).to.have.property('taxTypeSGST');
        // expect(instance.taxTypeSGST).to.be(expectedValueLiteral);
      });

      it('should have the property taxTypeIGST (base name: "TaxTypeIGST")', function() {
        // TODO: update the code to test the property taxTypeIGST
        expect(instance).to.have.property('taxTypeIGST');
        // expect(instance.taxTypeIGST).to.be(expectedValueLiteral);
      });

      it('should have the property totalExpense (base name: "TotalExpense")', function() {
        // TODO: update the code to test the property totalExpense
        expect(instance).to.have.property('totalExpense');
        // expect(instance.totalExpense).to.be(expectedValueLiteral);
      });

    });
  });

}));
