/*
 * Selling Partner API for Finances
 * The Selling Partner API for Finances provides financial information that is relevant to a seller's business. You can obtain financial events for a given order, financial event group, or date range without having to wait until a statement period closes. You can also obtain financial event groups for a given date range. 
 *
 * OpenAPI spec version: v0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.29
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../../src/financesV0/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../../src/financesV0/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SellingPartnerApiForFinances);
  }
}(this, function(expect, SellingPartnerApiForFinances) {
  'use strict';

  var instance;

  describe('financesV0', function() {
    describe('ChargeRefundEvent', function() {
      beforeEach(function() {
        instance = new SellingPartnerApiForFinances.ChargeRefundEvent();
      });

      it('should create an instance of ChargeRefundEvent', function() {
        // TODO: update the code to test ChargeRefundEvent
        expect(instance).to.be.a(SellingPartnerApiForFinances.ChargeRefundEvent);
      });

      it('should have the property postedDate (base name: "PostedDate")', function() {
        // TODO: update the code to test the property postedDate
        expect(instance).to.have.property('postedDate');
        // expect(instance.postedDate).to.be(expectedValueLiteral);
      });

      it('should have the property reasonCode (base name: "ReasonCode")', function() {
        // TODO: update the code to test the property reasonCode
        expect(instance).to.have.property('reasonCode');
        // expect(instance.reasonCode).to.be(expectedValueLiteral);
      });

      it('should have the property reasonCodeDescription (base name: "ReasonCodeDescription")', function() {
        // TODO: update the code to test the property reasonCodeDescription
        expect(instance).to.have.property('reasonCodeDescription');
        // expect(instance.reasonCodeDescription).to.be(expectedValueLiteral);
      });

      it('should have the property chargeRefundTransactions (base name: "ChargeRefundTransactions")', function() {
        // TODO: update the code to test the property chargeRefundTransactions
        expect(instance).to.have.property('chargeRefundTransactions');
        // expect(instance.chargeRefundTransactions).to.be(expectedValueLiteral);
      });

    });
  });

}));
