/*
 * Selling Partner API for Retail Procurement Payments
 * The Selling Partner API for Retail Procurement Payments provides programmatic access to vendors payments data.
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.29
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../../src/vendorInvoices/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../../src/vendorInvoices/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SellingPartnerApiForRetailProcurementPayments);
  }
}(this, function(expect, SellingPartnerApiForRetailProcurementPayments) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new SellingPartnerApiForRetailProcurementPayments.VendorPaymentsApi();
  });

  describe('vendorInvoices', function() {
    describe('VendorPaymentsApi', function() {
      describe('submitInvoices', function() {
        it('should call submitInvoices successfully', function(done) {
          // TODO: uncomment, update parameter values for submitInvoices call and complete the assertions
          /*
          var body = new SellingPartnerApiForRetailProcurementPayments.SubmitInvoicesRequest();
          body.invoices = [new SellingPartnerApiForRetailProcurementPayments.Invoice()];
          body.invoices[0].invoiceType = "Invoice";
          body.invoices[0].id = "";
          body.invoices[0].referenceNumber = "";
          body.invoices[0]._date = ;
          body.invoices[0].remitToParty = new SellingPartnerApiForRetailProcurementPayments.PartyIdentification();
          body.invoices[0].remitToParty.partyId = "";
          body.invoices[0].remitToParty.address = new SellingPartnerApiForRetailProcurementPayments.Address();
          body.invoices[0].remitToParty.address.name = "";
          body.invoices[0].remitToParty.address.addressLine1 = "";
          body.invoices[0].remitToParty.address.addressLine2 = "";
          body.invoices[0].remitToParty.address.addressLine3 = "";
          body.invoices[0].remitToParty.address.city = "";
          body.invoices[0].remitToParty.address.county = "";
          body.invoices[0].remitToParty.address.district = "";
          body.invoices[0].remitToParty.address.stateOrRegion = "";
          body.invoices[0].remitToParty.address.postalOrZipCode = "";
          body.invoices[0].remitToParty.address.countryCode = "";
          body.invoices[0].remitToParty.address.phone = "";
          body.invoices[0].remitToParty.taxRegistrationDetails = [new SellingPartnerApiForRetailProcurementPayments.TaxRegistrationDetails()];
          body.invoices[0].remitToParty.taxRegistrationDetails[0].taxRegistrationType = "VAT";
          body.invoices[0].remitToParty.taxRegistrationDetails[0].taxRegistrationNumber = "";
          body.invoices[0].shipToParty = new SellingPartnerApiForRetailProcurementPayments.PartyIdentification();
          body.invoices[0].shipToParty.partyId = "";
          body.invoices[0].shipToParty.address = new SellingPartnerApiForRetailProcurementPayments.Address();
          body.invoices[0].shipToParty.address.name = "";
          body.invoices[0].shipToParty.address.addressLine1 = "";
          body.invoices[0].shipToParty.address.addressLine2 = "";
          body.invoices[0].shipToParty.address.addressLine3 = "";
          body.invoices[0].shipToParty.address.city = "";
          body.invoices[0].shipToParty.address.county = "";
          body.invoices[0].shipToParty.address.district = "";
          body.invoices[0].shipToParty.address.stateOrRegion = "";
          body.invoices[0].shipToParty.address.postalOrZipCode = "";
          body.invoices[0].shipToParty.address.countryCode = "";
          body.invoices[0].shipToParty.address.phone = "";
          body.invoices[0].shipToParty.taxRegistrationDetails = [new SellingPartnerApiForRetailProcurementPayments.TaxRegistrationDetails()];
          body.invoices[0].shipToParty.taxRegistrationDetails[0].taxRegistrationType = "VAT";
          body.invoices[0].shipToParty.taxRegistrationDetails[0].taxRegistrationNumber = "";
          body.invoices[0].shipFromParty = new SellingPartnerApiForRetailProcurementPayments.PartyIdentification();
          body.invoices[0].shipFromParty.partyId = "";
          body.invoices[0].shipFromParty.address = new SellingPartnerApiForRetailProcurementPayments.Address();
          body.invoices[0].shipFromParty.address.name = "";
          body.invoices[0].shipFromParty.address.addressLine1 = "";
          body.invoices[0].shipFromParty.address.addressLine2 = "";
          body.invoices[0].shipFromParty.address.addressLine3 = "";
          body.invoices[0].shipFromParty.address.city = "";
          body.invoices[0].shipFromParty.address.county = "";
          body.invoices[0].shipFromParty.address.district = "";
          body.invoices[0].shipFromParty.address.stateOrRegion = "";
          body.invoices[0].shipFromParty.address.postalOrZipCode = "";
          body.invoices[0].shipFromParty.address.countryCode = "";
          body.invoices[0].shipFromParty.address.phone = "";
          body.invoices[0].shipFromParty.taxRegistrationDetails = [new SellingPartnerApiForRetailProcurementPayments.TaxRegistrationDetails()];
          body.invoices[0].shipFromParty.taxRegistrationDetails[0].taxRegistrationType = "VAT";
          body.invoices[0].shipFromParty.taxRegistrationDetails[0].taxRegistrationNumber = "";
          body.invoices[0].billToParty = new SellingPartnerApiForRetailProcurementPayments.PartyIdentification();
          body.invoices[0].billToParty.partyId = "";
          body.invoices[0].billToParty.address = new SellingPartnerApiForRetailProcurementPayments.Address();
          body.invoices[0].billToParty.address.name = "";
          body.invoices[0].billToParty.address.addressLine1 = "";
          body.invoices[0].billToParty.address.addressLine2 = "";
          body.invoices[0].billToParty.address.addressLine3 = "";
          body.invoices[0].billToParty.address.city = "";
          body.invoices[0].billToParty.address.county = "";
          body.invoices[0].billToParty.address.district = "";
          body.invoices[0].billToParty.address.stateOrRegion = "";
          body.invoices[0].billToParty.address.postalOrZipCode = "";
          body.invoices[0].billToParty.address.countryCode = "";
          body.invoices[0].billToParty.address.phone = "";
          body.invoices[0].billToParty.taxRegistrationDetails = [new SellingPartnerApiForRetailProcurementPayments.TaxRegistrationDetails()];
          body.invoices[0].billToParty.taxRegistrationDetails[0].taxRegistrationType = "VAT";
          body.invoices[0].billToParty.taxRegistrationDetails[0].taxRegistrationNumber = "";
          body.invoices[0].paymentTerms = new SellingPartnerApiForRetailProcurementPayments.PaymentTerms();
          body.invoices[0].paymentTerms.type = "Basic";
          body.invoices[0].paymentTerms.discountPercent = new SellingPartnerApiForRetailProcurementPayments.Decimal();
          body.invoices[0].paymentTerms.discountDueDays = ;
          body.invoices[0].paymentTerms.netDueDays = ;
          body.invoices[0].invoiceTotal = new SellingPartnerApiForRetailProcurementPayments.Money();
          body.invoices[0].invoiceTotal.currencyCode = "";
          body.invoices[0].invoiceTotal.amount = new SellingPartnerApiForRetailProcurementPayments.Decimal();
          body.invoices[0].taxDetails = [new SellingPartnerApiForRetailProcurementPayments.TaxDetails()];
          body.invoices[0].taxDetails[0].taxType = "CGST";
          body.invoices[0].taxDetails[0].taxRate = new SellingPartnerApiForRetailProcurementPayments.Decimal();
          body.invoices[0].taxDetails[0].taxAmount = new SellingPartnerApiForRetailProcurementPayments.Money();
          body.invoices[0].taxDetails[0].taxAmount.currencyCode = "";
          body.invoices[0].taxDetails[0].taxAmount.amount = new SellingPartnerApiForRetailProcurementPayments.Decimal();
          body.invoices[0].taxDetails[0].taxableAmount = new SellingPartnerApiForRetailProcurementPayments.Money();
          body.invoices[0].taxDetails[0].taxableAmount.currencyCode = "";
          body.invoices[0].taxDetails[0].taxableAmount.amount = new SellingPartnerApiForRetailProcurementPayments.Decimal();
          body.invoices[0].additionalDetails = [new SellingPartnerApiForRetailProcurementPayments.AdditionalDetails()];
          body.invoices[0].additionalDetails[0].type = "SUR";
          body.invoices[0].additionalDetails[0].detail = "";
          body.invoices[0].additionalDetails[0].languageCode = "";
          body.invoices[0].chargeDetails = [new SellingPartnerApiForRetailProcurementPayments.ChargeDetails()];
          body.invoices[0].chargeDetails[0].type = "Freight";
          body.invoices[0].chargeDetails[0].description = "";
          body.invoices[0].chargeDetails[0].chargeAmount = new SellingPartnerApiForRetailProcurementPayments.Money();
          body.invoices[0].chargeDetails[0].chargeAmount.currencyCode = "";
          body.invoices[0].chargeDetails[0].chargeAmount.amount = new SellingPartnerApiForRetailProcurementPayments.Decimal();
          body.invoices[0].chargeDetails[0].taxDetails = [new SellingPartnerApiForRetailProcurementPayments.TaxDetails()];
          body.invoices[0].chargeDetails[0].taxDetails[0].taxType = "CGST";
          body.invoices[0].chargeDetails[0].taxDetails[0].taxRate = new SellingPartnerApiForRetailProcurementPayments.Decimal();
          body.invoices[0].chargeDetails[0].taxDetails[0].taxAmount = new SellingPartnerApiForRetailProcurementPayments.Money();
          body.invoices[0].chargeDetails[0].taxDetails[0].taxAmount.currencyCode = "";
          body.invoices[0].chargeDetails[0].taxDetails[0].taxAmount.amount = new SellingPartnerApiForRetailProcurementPayments.Decimal();
          body.invoices[0].chargeDetails[0].taxDetails[0].taxableAmount = new SellingPartnerApiForRetailProcurementPayments.Money();
          body.invoices[0].chargeDetails[0].taxDetails[0].taxableAmount.currencyCode = "";
          body.invoices[0].chargeDetails[0].taxDetails[0].taxableAmount.amount = new SellingPartnerApiForRetailProcurementPayments.Decimal();
          body.invoices[0].allowanceDetails = [new SellingPartnerApiForRetailProcurementPayments.AllowanceDetails()];
          body.invoices[0].allowanceDetails[0].type = "Discount";
          body.invoices[0].allowanceDetails[0].description = "";
          body.invoices[0].allowanceDetails[0].allowanceAmount = new SellingPartnerApiForRetailProcurementPayments.Money();
          body.invoices[0].allowanceDetails[0].allowanceAmount.currencyCode = "";
          body.invoices[0].allowanceDetails[0].allowanceAmount.amount = new SellingPartnerApiForRetailProcurementPayments.Decimal();
          body.invoices[0].allowanceDetails[0].taxDetails = [new SellingPartnerApiForRetailProcurementPayments.TaxDetails()];
          body.invoices[0].allowanceDetails[0].taxDetails[0].taxType = "CGST";
          body.invoices[0].allowanceDetails[0].taxDetails[0].taxRate = new SellingPartnerApiForRetailProcurementPayments.Decimal();
          body.invoices[0].allowanceDetails[0].taxDetails[0].taxAmount = new SellingPartnerApiForRetailProcurementPayments.Money();
          body.invoices[0].allowanceDetails[0].taxDetails[0].taxAmount.currencyCode = "";
          body.invoices[0].allowanceDetails[0].taxDetails[0].taxAmount.amount = new SellingPartnerApiForRetailProcurementPayments.Decimal();
          body.invoices[0].allowanceDetails[0].taxDetails[0].taxableAmount = new SellingPartnerApiForRetailProcurementPayments.Money();
          body.invoices[0].allowanceDetails[0].taxDetails[0].taxableAmount.currencyCode = "";
          body.invoices[0].allowanceDetails[0].taxDetails[0].taxableAmount.amount = new SellingPartnerApiForRetailProcurementPayments.Decimal();
          body.invoices[0].items = [new SellingPartnerApiForRetailProcurementPayments.InvoiceItem()];
          body.invoices[0].items[0].itemSequenceNumber = 0;
          body.invoices[0].items[0].amazonProductIdentifier = "";
          body.invoices[0].items[0].vendorProductIdentifier = "";
          body.invoices[0].items[0].invoicedQuantity = new SellingPartnerApiForRetailProcurementPayments.ItemQuantity();
          body.invoices[0].items[0].invoicedQuantity.amount = 0;
          body.invoices[0].items[0].invoicedQuantity.unitOfMeasure = "Cases";
          body.invoices[0].items[0].invoicedQuantity.unitSize = 0;
          body.invoices[0].items[0].netCost = new SellingPartnerApiForRetailProcurementPayments.Money();
          body.invoices[0].items[0].netCost.currencyCode = "";
          body.invoices[0].items[0].netCost.amount = new SellingPartnerApiForRetailProcurementPayments.Decimal();
          body.invoices[0].items[0].purchaseOrderNumber = "";
          body.invoices[0].items[0].hsnCode = "";
          body.invoices[0].items[0].creditNoteDetails = new SellingPartnerApiForRetailProcurementPayments.CreditNoteDetails();
          body.invoices[0].items[0].creditNoteDetails.referenceInvoiceNumber = "";
          body.invoices[0].items[0].creditNoteDetails.debitNoteNumber = "";
          body.invoices[0].items[0].creditNoteDetails.returnsReferenceNumber = "";
          body.invoices[0].items[0].creditNoteDetails.goodsReturnDate = ;
          body.invoices[0].items[0].creditNoteDetails.rmaId = "";
          body.invoices[0].items[0].creditNoteDetails.coopReferenceNumber = "";
          body.invoices[0].items[0].creditNoteDetails.consignorsReferenceNumber = "";
          body.invoices[0].items[0].taxDetails = [new SellingPartnerApiForRetailProcurementPayments.TaxDetails()];
          body.invoices[0].items[0].taxDetails[0].taxType = "CGST";
          body.invoices[0].items[0].taxDetails[0].taxRate = new SellingPartnerApiForRetailProcurementPayments.Decimal();
          body.invoices[0].items[0].taxDetails[0].taxAmount = new SellingPartnerApiForRetailProcurementPayments.Money();
          body.invoices[0].items[0].taxDetails[0].taxAmount.currencyCode = "";
          body.invoices[0].items[0].taxDetails[0].taxAmount.amount = new SellingPartnerApiForRetailProcurementPayments.Decimal();
          body.invoices[0].items[0].taxDetails[0].taxableAmount = new SellingPartnerApiForRetailProcurementPayments.Money();
          body.invoices[0].items[0].taxDetails[0].taxableAmount.currencyCode = "";
          body.invoices[0].items[0].taxDetails[0].taxableAmount.amount = new SellingPartnerApiForRetailProcurementPayments.Decimal();
          body.invoices[0].items[0].chargeDetails = [new SellingPartnerApiForRetailProcurementPayments.ChargeDetails()];
          body.invoices[0].items[0].chargeDetails[0].type = "Freight";
          body.invoices[0].items[0].chargeDetails[0].description = "";
          body.invoices[0].items[0].chargeDetails[0].chargeAmount = new SellingPartnerApiForRetailProcurementPayments.Money();
          body.invoices[0].items[0].chargeDetails[0].chargeAmount.currencyCode = "";
          body.invoices[0].items[0].chargeDetails[0].chargeAmount.amount = new SellingPartnerApiForRetailProcurementPayments.Decimal();
          body.invoices[0].items[0].chargeDetails[0].taxDetails = [new SellingPartnerApiForRetailProcurementPayments.TaxDetails()];
          body.invoices[0].items[0].chargeDetails[0].taxDetails[0].taxType = "CGST";
          body.invoices[0].items[0].chargeDetails[0].taxDetails[0].taxRate = new SellingPartnerApiForRetailProcurementPayments.Decimal();
          body.invoices[0].items[0].chargeDetails[0].taxDetails[0].taxAmount = new SellingPartnerApiForRetailProcurementPayments.Money();
          body.invoices[0].items[0].chargeDetails[0].taxDetails[0].taxAmount.currencyCode = "";
          body.invoices[0].items[0].chargeDetails[0].taxDetails[0].taxAmount.amount = new SellingPartnerApiForRetailProcurementPayments.Decimal();
          body.invoices[0].items[0].chargeDetails[0].taxDetails[0].taxableAmount = new SellingPartnerApiForRetailProcurementPayments.Money();
          body.invoices[0].items[0].chargeDetails[0].taxDetails[0].taxableAmount.currencyCode = "";
          body.invoices[0].items[0].chargeDetails[0].taxDetails[0].taxableAmount.amount = new SellingPartnerApiForRetailProcurementPayments.Decimal();
          body.invoices[0].items[0].allowanceDetails = [new SellingPartnerApiForRetailProcurementPayments.AllowanceDetails()];
          body.invoices[0].items[0].allowanceDetails[0].type = "Discount";
          body.invoices[0].items[0].allowanceDetails[0].description = "";
          body.invoices[0].items[0].allowanceDetails[0].allowanceAmount = new SellingPartnerApiForRetailProcurementPayments.Money();
          body.invoices[0].items[0].allowanceDetails[0].allowanceAmount.currencyCode = "";
          body.invoices[0].items[0].allowanceDetails[0].allowanceAmount.amount = new SellingPartnerApiForRetailProcurementPayments.Decimal();
          body.invoices[0].items[0].allowanceDetails[0].taxDetails = [new SellingPartnerApiForRetailProcurementPayments.TaxDetails()];
          body.invoices[0].items[0].allowanceDetails[0].taxDetails[0].taxType = "CGST";
          body.invoices[0].items[0].allowanceDetails[0].taxDetails[0].taxRate = new SellingPartnerApiForRetailProcurementPayments.Decimal();
          body.invoices[0].items[0].allowanceDetails[0].taxDetails[0].taxAmount = new SellingPartnerApiForRetailProcurementPayments.Money();
          body.invoices[0].items[0].allowanceDetails[0].taxDetails[0].taxAmount.currencyCode = "";
          body.invoices[0].items[0].allowanceDetails[0].taxDetails[0].taxAmount.amount = new SellingPartnerApiForRetailProcurementPayments.Decimal();
          body.invoices[0].items[0].allowanceDetails[0].taxDetails[0].taxableAmount = new SellingPartnerApiForRetailProcurementPayments.Money();
          body.invoices[0].items[0].allowanceDetails[0].taxDetails[0].taxableAmount.currencyCode = "";
          body.invoices[0].items[0].allowanceDetails[0].taxDetails[0].taxableAmount.amount = new SellingPartnerApiForRetailProcurementPayments.Decimal();

          instance.submitInvoices(body).then(function(data) {
            // TODO: update response assertions
            expect(data).to.be.a(SellingPartnerApiForRetailProcurementPayments.SubmitInvoicesResponse);
            expect(data.payload).to.be.a(SellingPartnerApiForRetailProcurementPayments.TransactionId);
                  expect(data.payload.transactionId).to.be.a('string');
              // expect(data.payload.transactionId).to.be("");
            expect(data.errors).to.be.a(SellingPartnerApiForRetailProcurementPayments.ErrorList);
    
            done();
          }, function(error) {
            done(error);
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
