/*
 * Selling Partner API for Retail Procurement Orders
 * The Selling Partner API for Retail Procurement Orders provides programmatic access to vendor orders data.
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.29
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../../src/vendorOrders/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../../src/vendorOrders/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SellingPartnerApiForRetailProcurementOrders);
  }
}(this, function(expect, SellingPartnerApiForRetailProcurementOrders) {
  'use strict';

  var instance;

  describe('vendorOrders', function() {
    describe('ItemQuantity', function() {
      beforeEach(function() {
        instance = new SellingPartnerApiForRetailProcurementOrders.ItemQuantity();
      });

      it('should create an instance of ItemQuantity', function() {
        // TODO: update the code to test ItemQuantity
        expect(instance).to.be.a(SellingPartnerApiForRetailProcurementOrders.ItemQuantity);
      });

      it('should have the property amount (base name: "amount")', function() {
        // TODO: update the code to test the property amount
        expect(instance).to.have.property('amount');
        // expect(instance.amount).to.be(expectedValueLiteral);
      });

      it('should have the property unitOfMeasure (base name: "unitOfMeasure")', function() {
        // TODO: update the code to test the property unitOfMeasure
        expect(instance).to.have.property('unitOfMeasure');
        // expect(instance.unitOfMeasure).to.be(expectedValueLiteral);
      });

      it('should have the property unitSize (base name: "unitSize")', function() {
        // TODO: update the code to test the property unitSize
        expect(instance).to.have.property('unitSize');
        // expect(instance.unitSize).to.be(expectedValueLiteral);
      });

    });
  });

}));
