/*
 * Selling Partner API for Listings Restrictions
 * The Selling Partner API for Listings Restrictions provides programmatic access to restrictions on Amazon catalog listings.  For more information, see the [Listings Restrictions API Use Case Guide](doc:listings-restrictions-api-v2021-08-01-use-case-guide).
 *
 * OpenAPI spec version: 2021-08-01
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.29
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../../src/listingsRestrictions_2021-08-01/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../../src/listingsRestrictions_2021-08-01/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SellingPartnerApiForListingsRestrictions);
  }
}(this, function(expect, SellingPartnerApiForListingsRestrictions) {
  'use strict';

  var instance;

  describe('listingsRestrictions_2021-08-01', function() {
    describe('Link', function() {
      beforeEach(function() {
        instance = new SellingPartnerApiForListingsRestrictions.Link();
      });

      it('should create an instance of Link', function() {
        // TODO: update the code to test Link
        expect(instance).to.be.a(SellingPartnerApiForListingsRestrictions.Link);
      });

      it('should have the property resource (base name: "resource")', function() {
        // TODO: update the code to test the property resource
        expect(instance).to.have.property('resource');
        // expect(instance.resource).to.be(expectedValueLiteral);
      });

      it('should have the property verb (base name: "verb")', function() {
        // TODO: update the code to test the property verb
        expect(instance).to.have.property('verb');
        // expect(instance.verb).to.be(expectedValueLiteral);
      });

      it('should have the property title (base name: "title")', function() {
        // TODO: update the code to test the property title
        expect(instance).to.have.property('title');
        // expect(instance.title).to.be(expectedValueLiteral);
      });

      it('should have the property type (base name: "type")', function() {
        // TODO: update the code to test the property type
        expect(instance).to.have.property('type');
        // expect(instance.type).to.be(expectedValueLiteral);
      });

    });
  });

}));
